/**
 * DO NOT MODIFY THIS CODE
 *
 * Place all of your changes in TaxLine.java
 *
 * It has been machine generated from fixtures and your changes will be
 * lost if anything new needs to be added to the API.
 **/
// Last Generated: 2011-09-26T15:53:49-04:00
package com.haravan.api.resources;

import java.util.List;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * This code has been machine generated by processing the single entry
 * fixtures found from the Haravan API Documentation
 */

public class MGTaxLine extends HaravanResource {

	@JsonProperty("price")
	public String getPrice() {
		return (String)getAttribute("price");
	}
	@JsonProperty("price")
	public void setPrice(String _price) {
		setAttribute("price", _price);
	}

	@JsonProperty("rate")
	public double getRate() {
		Double value = (Double)getAttribute("rate");
		return value != null ? value : 0.0;
	}
	@JsonProperty("rate")
	public void setRate(double _rate) {
		setAttribute("rate", _rate);
	}

	@JsonProperty("title")
	public String getTitle() {
		return (String)getAttribute("title");
	}
	@JsonProperty("title")
	public void setTitle(String _title) {
		setAttribute("title", _title);
	}

}
