// Last Generated: 2011-08-25T23:29:48-04:00
package com.haravan.api.resources;

import org.codehaus.jackson.annotate.JsonProperty;

/**
* This code has been machine generated by processing the single entry
* fixtures found from the Haravan API Documentation
*/
  
public class ShippingLine extends MGShippingLine {

}