package com.haravan.api.resources;

import org.codehaus.jackson.annotate.JsonProperty;

/**
* This code has been machine generated by processing the single entry
* fixtures found from the Haravan API Documentation
*/
  
public class Shop extends MGShop {

}